### ISSUE TITLE
Schedule bug

### ISSUE THREAD

**Issue by rtnpro** [fedora-infra/statscache#10]
@ralphbean ,

I think I stumbled across a bug in `statscache.schedule.Schedule`. I am not sure if it's a bug or feature :\

```
import datetime
import statscache.schedule

s = statscache.schedule.Schedule(minute=[0, 15, 30, 45])
now = datetime.datetime.strptime('2014-12-23 13:00', '%Y-%m-%d %H:%M')
s.next(now) # returns datetime.datetime(2014, 12, 23, 13, 0, 1)
s.next(s.next(now)) #returns datetime.datetime(2014, 12, 23, 13, 0, 2)

now = datetime.datetime.strptime('2014-12-23 13:01', '%Y-%m-%d %H:%M')
s.next(now) #returns datetime.datetime(2014, 12, 23, 13, 15, 1)
```

By initializing the above schedule, I want to run something every 15th minute of an hour, every hour. However, I see that, since I do not supply any `second` value, the schedule will run every second for the entire 15th minute. Is this a desired behaviour? Please correct me if I am wrong.

Let's say that the priority order of Schedule params is: `hour > minute > second`. If I initialize a schedule with a param, say `minute`, then we should accept default values for a higher param `hour` and not consider any values for a param with less priority: `second`. So, the above schedule will run every hour at the specified minutes.

Does it make sense?

**Comment by ralphbean** [comment]
> Is this a desired behaviour? Please correct me if I am wrong.

Well, "yes".

I was trying to copy how cron works.  And this is how cron works.  However, cron doesn't do anything with seconds (only minutes, hours and upwards).

> Let's say that the priority order of Schedule params is: hour > minute > second. If I initialize a schedule with a param, say minute, then we should accept default values for a higher param hour and not consider any values for a param with less priority: second. So, the above schedule will run every hour at the specified minutes.

Let's do this.  I'll come up with an implementation.
