### ISSUE TITLE
Allow plugins decide frequency of execution

### ISSUE THREAD

**Issue by rtnpro** [fedora-infra/statscache#2]
I think we should allow plugins to have some control over the frequency of the producer handling messages. For example, in case of plugin for release engineering dashboard, we need to dump a message to DB only once, and the timestamp won't be the producer run timestamp, but the timestamp of the message.

@ralphbean please verify this issue and share your thoughts.

**Comment by ralphbean** [comment]
:+1:.

I'm not yet sure how to go about it, but if you have an idea of how to model and implement it, go for it!
